### ISSUE TITLE
bug in the quick attribute change tool

### ISSUE THREAD

**Issue by eunaotenhoid** [kaileymsnay/qte#2]
I caught a small bug in the quick attribute change tool, when you change an attribute the previous one doesn't disappear

**Comment by melvingb** [comment]
That bug has always been there, the previous developer's version also had it, hopefully Kailey will be able to fix it for future releases.

**Comment by kaileymsnay** [comment]
Can you explain the steps to reproduce this? I just tested on my local board and it functions as expected.

**Comment by melvingb** [comment]
> Can you explain the steps to reproduce this? I just tested on my local board and it functions as expected.

Personally, the detail that I have had is that when being in a topic and assigning the attribute, it assigns it well, but when removing it from the tool it is apparently removed, but if you press f5 the attribute is still there.

1) 
![imagen](https://github.com/user-attachments/assets/dbc6df69-2f1e-4adf-82c0-df982c12d6a7)

2)
![imagen](https://github.com/user-attachments/assets/b3e1585f-07f6-4561-a2da-0b68a37f27fa)

3)
https://github.com/user-attachments/assets/8cac23a0-a556-4f93-a6db-c3b4eb327d13


I hope you can understand what I mean

**Comment by kaileymsnay** [comment]
I can't reproduce this on my board; even after pressing F5 the deleted attribute is removed. This might be a style issue. Does this happen in prosilver? I notice that you don't get the alert box like you should when assigning/removing an attribute (as indicated in your video).

![alert_box](https://github.com/user-attachments/assets/19be466c-4976-4cf6-a5f0-c233f5c2abfb)

**Comment by melvingb** [comment]
In prosilver is the same issue

https://github.com/user-attachments/assets/696f8ad5-aae9-4ee8-affd-dcdecc119f2c

**Comment by kaileymsnay** [comment]
You're still not getting the alert box. What version of the extension are you using? Are you blocking jquery?

**Comment by melvingb** [comment]
> You're still not getting the alert box. What version of the extension are you using? Are you blocking jquery?

The last version from the extension,  
![imagen](https://github.com/user-attachments/assets/8e12df21-11b9-40a9-8154-ea67db412899)

I am not blocking jquery, i have already deactivated all the extensions and left only qte and the same error persists, I don't know if your version has something different, in particular it doesn't work for me.

**Comment by kaileymsnay** [comment]
Still not sure what's going on, but try this change and let me know if it works.

Open: `qte.php`

Find and delete (around line 388):
```		meta_refresh(3, $viewtopic_url);```

Find (around line 406):
```		trigger_error($message);```

After, add:
```		meta_refresh(3, $viewtopic_url);```

**Comment by melvingb** [comment]
The problem persist

What I have done and it is not recommended was to comment this line

`		if (!$s_edit && $attribute_id != self::DELETE || !$s_delete && $attribute_id == self::DELETE)
		{
			//return;
		}`
		
By commenting that line if the attribute removal works perfectly, but there I am skipping security code.

`/**
	 * Change topic attribute
	 */
	public function attr_apply($attribute_id = 0, $topic_id = 0, $forum_id = 0, $topic_attribute = 0, $author_id = 0, $viewtopic_url = '')
	{
		if (empty($topic_id) || empty($forum_id) || empty($attribute_id))
		{
			return;
		}

		$s_edit = $this->auth->acl_get('m_qte_attr_edit', $forum_id) || $this->auth->acl_get('f_qte_attr_' . $attribute_id, $forum_id) && $this->user->data['is_registered'] && $this->user->data['user_id'] == $author_id;
		$s_delete = $this->auth->acl_get('m_qte_attr_delete', $forum_id);

		if (!$s_edit && $attribute_id != self::DELETE || !$s_delete && $attribute_id == self::DELETE)
		{
			return;
		}

		// Default values
		$fields = [
			'topic_attr_id'		=> 0,
			'topic_attr_user'	=> 0,
			'topic_attr_time'	=> 0,
		];

		$current_time = time();

		if ($attribute_id != self::DELETE)
		{
			$fields = [
				'topic_attr_id'		=> $attribute_id,
				'topic_attr_user'	=> $this->user->data['user_id'],
				'topic_attr_time'	=> $current_time,
			];
		}

		$sql = 'UPDATE ' . $this->table_prefix . 'topics
			SET ' . $this->db->sql_build_array('UPDATE', $fields) . '
			WHERE topic_id = ' . (int) $topic_id;
		$this->db->sql_query($sql);

		$sql = 'SELECT topic_id
			FROM ' . $this->table_prefix . 'topics
			WHERE topic_moved_id = ' . (int) $topic_id;
		$result = $this->db->sql_query($sql);
		$shadow_topic_id = (int) $this->db->sql_fetchfield('topic_id');
		$this->db->sql_freeresult($result);

		if (!empty($shadow_topic_id))
		{
			$sql = 'UPDATE ' . $this->table_prefix . 'topics
				SET ' . $this->db->sql_build_array('UPDATE', $fields) . '
				WHERE topic_id = ' . (int) $shadow_topic_id;
			$this->db->sql_query($sql);
		}

		meta_refresh(3, $viewtopic_url);

		$message = $this->language->lang('QTE_ATTRIBUTE_' . ($attribute_id == -1 ? 'DELETED' : (empty($topic_attribute) ? 'ADDED' : 'UPDATED')));

		if ($this->request->is_ajax())
		{
			$json_response = new \phpbb\json_response;
			$json_response->send([
				'success'	=> true,

				'MESSAGE_TITLE'	=> $this->language->lang('INFORMATION'),
				'MESSAGE_TEXT'	=> $message,
				'NEW_ATTRIBUTE'	=> $this->attr_display($attribute_id, $this->user->data['user_id'], $current_time),
			]);
		}

		$message .= '<br /><br />' . $this->language->lang('RETURN_PAGE', '<a href="' . $viewtopic_url . '">', '</a>');

		trigger_error($message);
	}`
	
This is the complete function

If you need access to the ftp let me know and I will gladly give you the access, it is difficult to decipher the error when it does not happen to you, it has happened to me.

**Comment by kaileymsnay** [comment]
Is this as a moderator on another user's topic or as a user on your own topic? I'm wondering if the check for `self::DELETE` is needed.

**Comment by melvingb** [comment]
> Is this as a moderator on another user's topic or as a user on your own topic? I'm wondering if the check for `self::DELETE` is needed.

It's my own topic

**Comment by kaileymsnay** [comment]
Alright, that helps. Give me about 48 hours to check a few things and I'll let you know.

**Comment by melvingb** [comment]
Thank you for your support

**Comment by kaileymsnay** [comment]
Might just be easier to throw an error.

FIND:
```
if (!$s_edit && $attribute_id != self::DELETE || !$s_delete && $attribute_id == self::DELETE)
{
	return;
}
```

REPLACE WITH:
```
if (!$s_edit && $attribute_id != self::DELETE || !$s_delete && $attribute_id == self::DELETE)
{
	trigger_error($this->language->lang('NOT_AUTHORISED'));
}
```

If you get an error, that could mean your permissions are not set correctly.

**Comment by melvingb** [comment]
What I have seen that in previous version to phpBB 3.3.14 if it works, for example I have a forum running in 3.3.11 and if it works perfectly, but in the new version does not, now I do not have the computer at hand to give you more information.

**Comment by melvingb** [comment]
> If you get an error, that could mean your permissions are not set correctly.

Indeed, it returns me permissions error, but if the permissions according to me I have placed them well hahaa

![Captura de pantalla 2024-12-30 185316](https://github.com/user-attachments/assets/fdfe5d4a-0263-4deb-8dc4-6a2c7ffa7d5b)

I have uninstalled the extension again and reinstalled it, I have configured the necessary permissions and I still get the same error.

**Comment by melvingb** [comment]
And yes, you were absolutely right Kailey, it is not a bug what happens here, what is missing is the correct configuration of the moderative permissions of the groups in the forums where the attributes are going to be used, thank for your help.

![imagen](https://github.com/user-attachments/assets/69642957-e454-4da7-84c6-7e739064ba58)
